# Generated by Django 5.1.5 on 2025-03-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='gender_type',
            new_name='gender',
        ),
    ]
